export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREASE_ITEM_QTY = "INCREASE_ITEM_QTY";
export const DECREASE_ITEM_QTY = "DECREASE_ITEM_QTY";
export const DELETE_ITEM = "DELETE_ITEM";
export const CLEAR_CART = "CLEAR_CART";